import i18n from '../Locales/i18n';

export const Messages = {
  server_error: 'Something went wrong, please try again',
  no_internet: 'No internet, please check your internet',
  logout_message: 'Are you sure you want to logout?',
  openSettingForLocation: 'Please allow location access from your setting',
  openSetting: 'Please allow camera or photo library access from your setting',
  ValidEmail: 'Please enter valid email',
  Email: 'Please enter email',
  OTP: 'Please enter OTP',
  Password: 'Please enter password',
  SpaceInPassword: 'Password does not allow space',
  CPassword: 'Please enter confirm password',
  OldPassword: 'Please enter old password',
  NewPassword: 'Please enter new password',
  PasswordLength: 'Password should have at least 6 characters',
  PasswordNotMatch: 'Confirm password not match with password',
  ValidName: 'Please enter name',
  ShortPassword: 'Too short password',
  Address: 'Please enter address',
  Mobile: 'Please enter phone number',
  PhoneNumber: 'Please enter valid phone number',
  InValidPhoneNumber: 'Invalid Phone number',
  InValidMobileNumber: 'Invalid Mobile number',
  InValidLandlineNumber: 'Invalid Landline number',
  ValidNumber: 'Please enter valid number',
  City: 'Please enter city',
  State: 'Please enter state',
  Country: 'Please enter country',
  DOB: 'Please Select DOB',
  Pincode: 'Please enter pincode',
  InvalidPincode: 'Please enter valid pincode',
  TermCondition: 'Please check Terms & Condition',
  CameraAssess: 'Open setting for camera asscess permission',
  ForgotSuccessMessage: 'We have sent new password on your email, Please check your email',
  CameraEnableAccess: 'Please enable camera permission',
  Gender: 'Please select gender',
  validOTP: 'Please enter valid OTP',
  validFirstName: 'Please enter first name',
  validLastName: 'Please enter last name',
};

export const Keys = {
  password: 'password',
  email: 'email',
  firstName: 'firstName',
  lastName: 'lastName',
  confirmPassword: 'confirmPassword',
  mobile: 'mobile',
  currentPassword: 'currentPassword',
  newPassword: 'newPassword',
  address: 'address',
  code: 'code',
  titleAd: 'adTitle',
  adDesc: 'adDescription',
  hastags: 'hastag',
  name: 'name',
  message: 'message',
  location: 'location',
  dob: 'dob',
};
