export const Placeholders = {
  getStarted: 'Get Started',
  login: 'Log In',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  dontHaveAccount: "Don't have an account?",

  // Placeholders for textinput
  email: 'Enter your email',
  passoword: 'Enter your password',

  // GENERAL
  skip: 'Skip',
  continue: 'Continue',
  submit: 'Submit',
  register: 'Register',
  ok: 'Ok',
  cancel: 'Cancel',
  home: 'Home',
  profile: 'Profile',
  logout: 'Logout',
  verify: 'Verify',
  viewAll: 'View All',
  createPassword: 'Create Password',
  comment: 'Comment',
  sendMessage: 'Send Message',
  name: 'Full Name',

  //   LOGIN STACK
  pleaseLogin: 'Please log in to your account',
  forgotPassword: 'Forgot Password?',
  emailAddress: 'Email Address',
  password: 'Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  mobileNumber: 'Mobile Number',
  alreadyAccount: 'Already registered with us?',
  createAccount: 'Sign Up',
  forgotContent: "Enter your registered email account and we'll send you verification code to reset password",
  send: 'Send',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  resetPassContent: 'Enter OTP which has been sent to your registered email address',
  resetPassword: 'Reset Your Password',
  verifyMobile: 'Verify your email address',
  verifyMobileContent: 'Enter OTP which has been sent to your registered email address',
  rememberMe: 'Remember Me',
};
